name: "Bambuddy"
version: "0.2.4.2"
slug: "bambuddy"
description: "Local Bambuddy Add-on"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false

ingress: true
ingress_port: 8000
ingress_stream: false

panel_icon: "mdi:printer-3d"
panel_title: "Bambuddy"
panel_admin: false

ports:
  8000/tcp: null

map:
  - config:rw

options: {}
schema: {}

image: "ghcr.io/maziggy/bambuddy"
